TOPLEVEL_LANG = verilog
VERILOG_SOURCES = $(shell pwd)/../../source/BlackIceR32E.v $(shell pwd)/../../source/UART.v $(shell pwd)/../../source/Oak_R32I_top.v
TOPLEVEL = Oak_R32I_top
MODULE = test_BlackIceR32E

include $(shell cocotb-config --makefiles)/Makefile.sim
