TOPLEVEL_LANG = verilog
EXTRA_ARGS += --trace --trace-structs
VERILOG_SOURCES = $(shell pwd)/../source/ORC_R32I.v
TOPLEVEL = ORC_R32I
MODULE = top

include $(shell cocotb-config --makefiles)/Makefile.sim
